INSERT INTO produto VALUES (1,'Abóbora',1);
INSERT INTO produto VALUES (2,'Abobrinha',1);
INSERT INTO produto VALUES (3,'Acelga',1);
INSERT INTO produto VALUES (4,'Alcachofra',1);
INSERT INTO produto VALUES (5,'Alface americana',1);
INSERT INTO produto VALUES (6,'Alface crespa',1);
INSERT INTO produto VALUES (7,'Alface lisa',1);
INSERT INTO produto VALUES (8,'Alface roxa',1);
INSERT INTO produto VALUES (9,'Alfafa',1);
INSERT INTO produto VALUES (10,'Alho',1);
INSERT INTO produto VALUES (11,'Alho poró',1);
INSERT INTO produto VALUES (12,'Almeirão',1);
INSERT INTO produto VALUES (13,'Aspargos',1);
INSERT INTO produto VALUES (14,'Azedinha',1);
INSERT INTO produto VALUES (15,'Batata',1);
INSERT INTO produto VALUES (16,'Batata doce',1);
INSERT INTO produto VALUES (17,'Berinjela',1);
INSERT INTO produto VALUES (18,'Beterraba',1);
INSERT INTO produto VALUES (19,'Brócolis',1);
INSERT INTO produto VALUES (20,'Broto de alfafa',1);
INSERT INTO produto VALUES (21,'Broto de feijão',1);
INSERT INTO produto VALUES (22,'Broto de trevo',1);
INSERT INTO produto VALUES (23,'Cará',1);
INSERT INTO produto VALUES (24,'Catalonha',1);
INSERT INTO produto VALUES (25,'Cebola',1);
INSERT INTO produto VALUES (26,'Cebola roxa',1);
INSERT INTO produto VALUES (27,'Cebolete',1);
INSERT INTO produto VALUES (28,'Cebolinha',1);
INSERT INTO produto VALUES (29,'Cenoura',1);
INSERT INTO produto VALUES (30,'Chicória',1);
INSERT INTO produto VALUES (31,'Chuchu',1);
INSERT INTO produto VALUES (32,'Cogumelo paris',1);
INSERT INTO produto VALUES (33,'Cogumelo shimeji',1);
INSERT INTO produto VALUES (34,'Cogumelo shitake',1);
INSERT INTO produto VALUES (35,'Couve',1);
INSERT INTO produto VALUES (36,'Couve-de-bruxelas',1);
INSERT INTO produto VALUES (37,'Couve-flor',1);
INSERT INTO produto VALUES (38,'Echalota',1);
INSERT INTO produto VALUES (39,'Endívia',1);
INSERT INTO produto VALUES (40,'Erva-doce (Funcho)',1);
INSERT INTO produto VALUES (41,'Ervilha japonesa',1);
INSERT INTO produto VALUES (42,'Ervilha torta',1);
INSERT INTO produto VALUES (43,'Escarola',1);
INSERT INTO produto VALUES (44,'Espinafre',1);
INSERT INTO produto VALUES (45,'Fava',1);
INSERT INTO produto VALUES (46,'Gengibre',1);
INSERT INTO produto VALUES (47,'Inhame',1);
INSERT INTO produto VALUES (48,'Jalapeño',1);
INSERT INTO produto VALUES (49,'Jiló',1);
INSERT INTO produto VALUES (50,'Mandioca',1);
INSERT INTO produto VALUES (51,'Mandioquinha (Batata-baroa)',1);
INSERT INTO produto VALUES (52,'Milho',1);
INSERT INTO produto VALUES (53,'Mostarda',1);
INSERT INTO produto VALUES (54,'Nabo',1);
INSERT INTO produto VALUES (55,'Pepino comum',1);
INSERT INTO produto VALUES (56,'Pepino japonês',1);
INSERT INTO produto VALUES (57,'Pimentão',1);
INSERT INTO produto VALUES (58,'Pinhão',1);
INSERT INTO produto VALUES (59,'Quiabo',1);
INSERT INTO produto VALUES (60,'Rabanete',1);
INSERT INTO produto VALUES (61,'Radicchio',1);
INSERT INTO produto VALUES (62,'Repolho',1);
INSERT INTO produto VALUES (63,'Rúcula',1);
INSERT INTO produto VALUES (64,'Salsão',1);
INSERT INTO produto VALUES (65,'Tomate caqui',1);
INSERT INTO produto VALUES (66,'Tomate carmen',1);
INSERT INTO produto VALUES (67,'Tomate cereja',1);
INSERT INTO produto VALUES (68,'Tomate debora',1);
INSERT INTO produto VALUES (69,'Tomate italiano',1);
INSERT INTO produto VALUES (70,'Tomate pêra',1);
INSERT INTO produto VALUES (71,'Vagem holandesa',1);
INSERT INTO produto VALUES (72,'Vagem macarrão',1);
INSERT INTO produto VALUES (73,'Vagem manteiga',1);
INSERT INTO produto VALUES (74,'Alecrim',2);
INSERT INTO produto VALUES (75,'Cebolinha',2);
INSERT INTO produto VALUES (76,'Coentro',2);
INSERT INTO produto VALUES (77,'Dill',2);
INSERT INTO produto VALUES (78,'Estragão',2);
INSERT INTO produto VALUES (79,'Hortelã',2);
INSERT INTO produto VALUES (80,'Louro',2);
INSERT INTO produto VALUES (81,'Manjericão',2);
INSERT INTO produto VALUES (82,'Manjerona',2);
INSERT INTO produto VALUES (83,'Orégano',2);
INSERT INTO produto VALUES (84,'Salsinha',2);
INSERT INTO produto VALUES (85,'Sálvia',2);
INSERT INTO produto VALUES (86,'Tomilho',2);
INSERT INTO produto VALUES (87,'Abacate',3);
INSERT INTO produto VALUES (88,'Abacaxi havai',3);
INSERT INTO produto VALUES (89,'Abacaxi pérola',3);
INSERT INTO produto VALUES (90,'Ameixa preta',3);
INSERT INTO produto VALUES (91,'Ameixa rosada',3);
INSERT INTO produto VALUES (92,'Atemóia',3);
INSERT INTO produto VALUES (93,'Avocado',3);
INSERT INTO produto VALUES (94,'Banana baby',3);
INSERT INTO produto VALUES (95,'Banana da terra',3);
INSERT INTO produto VALUES (96,'Banana maçã',3);
INSERT INTO produto VALUES (97,'Banana nanica',3);
INSERT INTO produto VALUES (98,'Banana ouro',3);
INSERT INTO produto VALUES (99,'Banana prata',3);
INSERT INTO produto VALUES (100,'Cajú',3);
INSERT INTO produto VALUES (101,'Caqui chocolate',3);
INSERT INTO produto VALUES (102,'Caqui taubaté',3);
INSERT INTO produto VALUES (103,'Carambola',3);
INSERT INTO produto VALUES (104,'Cereja',3);
INSERT INTO produto VALUES (105,'Coco',3);
INSERT INTO produto VALUES (106,'Damasco',3);
INSERT INTO produto VALUES (107,'Figo',3);
INSERT INTO produto VALUES (108,'Fruta do conde',3);
INSERT INTO produto VALUES (109,'Goiaba branca',3);
INSERT INTO produto VALUES (110,'Goiaba vermelha',3);
INSERT INTO produto VALUES (111,'Granadilla',3);
INSERT INTO produto VALUES (112,'Grapefruit',3);
INSERT INTO produto VALUES (113,'Jabuticaba',3);
INSERT INTO produto VALUES (114,'Jaca',3);
INSERT INTO produto VALUES (115,'Jatobá',3);
INSERT INTO produto VALUES (116,'Kinkan',3);
INSERT INTO produto VALUES (117,'Kiwi',3);
INSERT INTO produto VALUES (118,'Laranja da terra',3);
INSERT INTO produto VALUES (119,'Laranja lima',3);
INSERT INTO produto VALUES (120,'Laranja pera',3);
INSERT INTO produto VALUES (121,'Lima da Pérsia',3);
INSERT INTO produto VALUES (122,'Limão siciliano',3);
INSERT INTO produto VALUES (123,'Limão Taiti',3);
INSERT INTO produto VALUES (124,'Maçã Fuji',3);
INSERT INTO produto VALUES (125,'Maçã gala',3);
INSERT INTO produto VALUES (126,'Maçã Ganny Smith',3);
INSERT INTO produto VALUES (127,'Maçã pink lady',3);
INSERT INTO produto VALUES (128,'Maçã verde',3);
INSERT INTO produto VALUES (129,'Macadâmia',3);
INSERT INTO produto VALUES (130,'Mamão formosa',3);
INSERT INTO produto VALUES (131,'Mamão golden',3);
INSERT INTO produto VALUES (132,'Mamão papaya',3);
INSERT INTO produto VALUES (133,'Manga bourbon',3);
INSERT INTO produto VALUES (134,'Manga haden',3);
INSERT INTO produto VALUES (135,'Manga keit',3);
INSERT INTO produto VALUES (136,'Manga palmer',3);
INSERT INTO produto VALUES (137,'Manga rosa',3);
INSERT INTO produto VALUES (138,'Manga Tommy',3);
INSERT INTO produto VALUES (139,'Manga Vandayke',3);
INSERT INTO produto VALUES (140,'Mangostin',3);
INSERT INTO produto VALUES (141,'Maracujá azedo',3);
INSERT INTO produto VALUES (142,'Maracujá doce',3);
INSERT INTO produto VALUES (143,'Marmelo',3);
INSERT INTO produto VALUES (144,'Melancia',3);
INSERT INTO produto VALUES (145,'Melancia baby',3);
INSERT INTO produto VALUES (146,'Melão amarelo',3);
INSERT INTO produto VALUES (147,'Melão doce',3);
INSERT INTO produto VALUES (148,'Melão espanhol',3);
INSERT INTO produto VALUES (149,'Melão Galia',3);
INSERT INTO produto VALUES (150,'Melão nectamelon',3);
INSERT INTO produto VALUES (151,'Melão orange',3);
INSERT INTO produto VALUES (152,'Melão ouro',3);
INSERT INTO produto VALUES (153,'Melão verde',3);
INSERT INTO produto VALUES (154,'Mexerica cravo',3);
INSERT INTO produto VALUES (155,'Mexerica ponkan',3);
INSERT INTO produto VALUES (156,'Mexerica Clemenville',3);
INSERT INTO produto VALUES (157,'Mexerica decopon',3);
INSERT INTO produto VALUES (158,'Mexerica do rio',3);
INSERT INTO produto VALUES (159,'Mexerica murkot',3);
INSERT INTO produto VALUES (160,'Morango',3);
INSERT INTO produto VALUES (161,'Nectarina',3);
INSERT INTO produto VALUES (162,'Pera abate fetel',3);
INSERT INTO produto VALUES (163,'Pera asiática',3);
INSERT INTO produto VALUES (164,'Pera bosc',3);
INSERT INTO produto VALUES (165,'Pera concord',3);
INSERT INTO produto VALUES (166,'Pera d''anjou',3);
INSERT INTO produto VALUES (167,'Pera packans',3);
INSERT INTO produto VALUES (168,'Pera portuguesa',3);
INSERT INTO produto VALUES (169,'Pera red',3);
INSERT INTO produto VALUES (170,'Pera williams',3);
INSERT INTO produto VALUES (171,'Pêssego',3);
INSERT INTO produto VALUES (172,'Romã',3);
INSERT INTO produto VALUES (173,'Sapoti',3);
INSERT INTO produto VALUES (174,'Tamarindo',3);
INSERT INTO produto VALUES (175,'Uva benitaka',3);
INSERT INTO produto VALUES (176,'Uva Brasil',3);
INSERT INTO produto VALUES (177,'Uva crismon',3);
INSERT INTO produto VALUES (178,'Uva cristima rosé',3);
INSERT INTO produto VALUES (179,'Uva Itália',3);
INSERT INTO produto VALUES (180,'Uva nacional sugraone',3);
INSERT INTO produto VALUES (181,'Uva red globe',3);
INSERT INTO produto VALUES (182,'Uva red mary',3);
INSERT INTO produto VALUES (183,'Uva rosada',3);
INSERT INTO produto VALUES (184,'Uva rubi',3);
INSERT INTO produto VALUES (185,'Uva thompson',3);